fic-scheduler:
  default-users:
    - username: "coordinator"
      password: "password"
      roles: ["COORDINATOR"]
      full-name: "Coordinator"
    - username: "admin"
      password: "adm1n"
      roles: ["DEBUG", "ADMIN", "COORDINATOR", "INSTRUCTOR"]
      full-name: "Admin User"

server:
  tomcat:
    accesslog:
      enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
