name: Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven Backend
        run: |
          cd FIC-Scheduler/backend
          mvn -B package --file pom.xml

      - name: Test with Maven
        run: |
          cd FIC-Scheduler/backend
          mvn test --file pom.xml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd FIC-Scheduler/frontend
          npm install

      - name: Build Frontend
        run: |
          cd FIC-Scheduler/frontend
          npm run build

      # - name: Test
      #   run: |
      #     cd FIC-Scheduler/frontend
      #     npm test
